### ISSUE TITLE
[April] Curation Workflow Tracking

### ISSUE THREAD

**Issue by aditigopalan** [mc2-center/data-models#101]
This ticket tracks curation workflow progression. 

Note: It is possible for work to take place simultaneously in the three sections with overlapping periods, allowing curation workflows for different months to coincide.

### **1. Curation and Annotation**
  - [x] Run Pubmed crawler to generate PublicationView manifest [205 publications generated, long sprint anticipated]
  - [x] Send Amber and Jineta a copy of the PublicationView manifest from latest crawl to review for MC2 Center Newsletter publication highlights
  - [x] Send Amber "News from CCKP" for MC2 Center Newsletter
  - [x] Annotate publications in PublicationView manifest [In progress]
  - [x] Generate ToolView and DatasetView manifests based on PublicationView manifest
  - [x] Run the [automated curation workflow](https://github.com/mc2-center/mc2-center-dcc/tree/main/annotations) to upload publications, datasets and tools [This includes splitting manifests, processing and validating manifests, generating target synapse IDs for upload, schema updates, upload to synapse and (in progress) a validation check for uploads)
  - [x] Generate UNION tables 
  - [x] QC of staging tables
  - [x] Performing automate portal sync to CCKP
  - [x] Validate data on the CCKP
  
  **Status check [Plan to report numbers for each category following pubmed crawl]:** 
  
  - [x] Publication upload [42]
  - [ ] Tool upload [1]
  - [x] Data set upload [20]

### **2. Data model**  
  - [x]  Update valid values in the data model and build
  - [ ]  Generate templates from new model
  - [x]  Release new model version [[v6.0.0](https://github.com/mc2-center/data-models/releases/tag/v6.0.0)]
  - [x]  Update DCA config [[PR here](https://github.com/Sage-Bionetworks/data_curator_config/pull/193)]

### **3. Contributor Engagement**
  - [ ] Emails to contributors (by grant) with info on newly added manifests, link to project, DCA, and instructions on review, annotation, validation, and submission, as applicable
  - [ ] Jira Help Desk ticket tracking, review, triage, with data model updates, as needed (TBD)
  - [ ] Annotation gap-filling of DatasetView and ToolView manifests

**Comment by aclayton555** [comment]
May have some data model changes, so will likely push with May curation batch.

note to Ashley: consider numbers on CCKP done for RPPR as of March curation batch.
