### ISSUE TITLE
[June] [Pubs] Curation Workflow Tracking

### ISSUE THREAD

**Issue by aditigopalan** [mc2-center/data-models#104]
This ticket tracks curation workflow progression. 

Note: It is possible for work to take place simultaneously in the three sections with overlapping periods, allowing curation workflows for different months to coincide.

### **1. Curation and Annotation**
  - [x] Run Pubmed crawler to generate PublicationView manifest [205 publications generated, long sprint anticipated]
  - [x] Send Amber and Jineta a copy of the PublicationView manifest from latest crawl to review for MC2 Center Newsletter publication highlights
  - [x] Send Amber "News from CCKP" for MC2 Center Newsletter
  - [x] Annotate publications in PublicationView manifest [In progress]
  - [x] Generate ToolView and DatasetView manifests based on PublicationView manifest
  - [x] Run the [automated curation workflow](https://github.com/mc2-center/mc2-center-dcc/tree/main/annotations) to upload publications, datasets and tools [This includes splitting manifests, processing and validating manifests, generating target synapse IDs for upload, schema updates, upload to synapse and (in progress) a validation check for uploads)
  - [x] Generate UNION tables 
  - [x] QC of staging tables
  - [x] Performing automate portal sync to CCKP
  - [x] Validate data on the CCKP
  
  **Status check [Plan to report numbers for each category following pubmed crawl]:** 
  
  - [x] Publication upload 

### **2. Data model**  [No new updates]
~~- [ ]  Update valid values in the data model and build~~
  ~~- [ ]  Generate templates from new model~~
  ~~- [ ]  Release new model version [no changes, no release]~~
  ~~- [ ]  Update DCA config [no changes, no update]~~

**Comment by aclayton555** [comment]
24-6 close out: aiming to upload May, April and June by mid 24-7/8 sprint. Will likely include a data model release during mid sprint

**Comment by aclayton555** [comment]
mid-sprint: 
- Pending Annotations still growing? @jaybee84  Check which resources have this. Not that "Pending Annotations" was historically implemented with publications that were not yet open access. But these are now also pushed to portal as an incentive for adding annotations to these resources.
- resume emails to contributors with existing documentation. Maybe targeted engagement to certain contributor

**Comment by jaybee84** [comment]
Publications: pending annotation for tumor type + assay (as discussed in the meeting mostly due to restricted access, but some on [open access](https://cancercomplexity.synapse.org/Explore/Publications?QueryWrapper0=%7B%22sql%22%3A%22SELECT+*+FROM+syn21868591%22%2C%22limit%22%3A25%2C%22selectedFacets%22%3A%5B%7B%22concreteType%22%3A%22org.sagebionetworks.repo.model.table.FacetColumnValuesRequest%22%2C%22columnName%22%3A%22tumorType%22%2C%22facetValues%22%3A%5B%22Pending+Annotation%22%5D%7D%2C%7B%22concreteType%22%3A%22org.sagebionetworks.repo.model.table.FacetColumnValuesRequest%22%2C%22columnName%22%3A%22tissue%22%2C%22facetValues%22%3A%5B%22Pending+Annotation%22%5D%7D%2C%7B%22concreteType%22%3A%22org.sagebionetworks.repo.model.table.FacetColumnValuesRequest%22%2C%22columnName%22%3A%22accessibility%22%2C%22facetValues%22%3A%5B%22Open+Access%22%5D%7D%5D%7D))
Datasets : pending annotations for [tissue](https://cancercomplexity.synapse.org/Explore/Datasets?QueryWrapper0=%7B%22sql%22%3A%22SELECT+*+FROM+syn21897968%22%2C%22limit%22%3A25%2C%22selectedFacets%22%3A%5B%7B%22concreteType%22%3A%22org.sagebionetworks.repo.model.table.FacetColumnValuesRequest%22%2C%22columnName%22%3A%22tissue%22%2C%22facetValues%22%3A%5B%22Pending+Annotation%22%5D%7D%5D%7D)
