### ISSUE TITLE
[July] [Pubs] Curation Workflow Tracking

### ISSUE THREAD

**Issue by aditigopalan** [mc2-center/data-models#131]
This ticket tracks curation workflow progression. 

Note: It is possible for work to take place simultaneously in the three sections with overlapping periods, allowing curation workflows for different months to coincide.

### **1. Curation and Annotation**
  - [x] Run Pubmed crawler to generate PublicationView manifest [205 publications generated, long sprint anticipated]
  - [x] Send Amber and Jineta a copy of the PublicationView manifest from latest crawl to review for MC2 Center Newsletter publication highlights
  - [x] Send Amber "News from CCKP" for MC2 Center Newsletter
  - [x] Annotate publications in PublicationView manifest [In progress]
  - [x] Generate ToolView and DatasetView manifests based on PublicationView manifest
  - [x] Run the [automated curation workflow](https://github.com/mc2-center/mc2-center-dcc/tree/main/annotations) to upload publications, datasets and tools [This includes splitting manifests, processing and validating manifests, generating target synapse IDs for upload, schema updates, upload to synapse and (in progress) a validation check for uploads)
  - [x] Generate UNION tables 
  - [x] QC of staging tables
  - [ ] Performing automate portal sync to CCKP
  - [x] Validate data on the CCKP
  
  **Status check [Plan to report numbers for each category following pubmed crawl]:** 
  
  - [x] Publication upload [ ]

No data model updates

**Comment by aclayton555** [comment]
Aiming to push sync of June, July and Aug resources in Sept.

Note: may be helpful to de-couple the publication curation from the datasets and tools curation so that we can push things when they are ready, rather than one causing a delay of the other. @aditigopalan will adjust tickets to account for resource type-specific tracking.

**Comment by aclayton555** [comment]
@aditigopalan can we close this?
