### ISSUE TITLE
[July - Sep] Dataset Curation Workflow Tracking

### ISSUE THREAD

**Issue by aditigopalan** [mc2-center/data-models#138]
This ticket tracks curation workflow progression. 

Note: It is possible for work to take place simultaneously in the three sections with overlapping periods, allowing curation workflows for different months to coincide.

### **1. Curation and Annotation**
  - [x] Run Pubmed crawler to generate PublicationView manifest [205 publications generated, long sprint anticipated]
  - [x] Send Amber and Jineta a copy of the PublicationView manifest from latest crawl to review for MC2 Center Newsletter publication highlights
  - [x] Send Amber "News from CCKP" for MC2 Center Newsletter
  - [x] Annotate publications in PublicationView manifest [In progress]
  - [x] Generate ToolView and DatasetView manifests based on PublicationView manifest
  - [x] Run the [automated curation workflow](https://github.com/mc2-center/mc2-center-dcc/tree/main/annotations) to upload publications, datasets and tools [This includes splitting manifests, processing and validating manifests, generating target synapse IDs for upload, schema updates, upload to synapse and (in progress) a validation check for uploads)
  - [ ] Generate UNION tables 
  - [ ] QC of staging tables
  - [ ] Performing automate portal sync to CCKP
  - [ ] Validate data on the CCKP
  
  **Status check [Plan to report numbers for each category following pubmed crawl]:** 
  
  - [x] Publication upload [ ]
  - [ ] Tool upload [ ]
  - [ ] Data set upload [ ]

### **2. Data model**  
  - [ ]  Update valid values in the data model and build
  - [ ]  Generate templates from new model
  - [ ]  Release new model version [no changes, no release]
  - [ ]  Update DCA config [no changes, no update]

### **3. Contributor Engagement**
  - [ ] Emails to contributors (by grant) with info on newly added manifests, link to project, DCA, and instructions on review, annotation, validation, and submission, as applicable
  - [ ] Jira Help Desk ticket tracking, review, triage, with data model updates, as needed (TBD)
  - [ ] Annotation gap-filling of DatasetView and ToolView manifests

**Comment by aclayton555** [comment]
24-11/12 Initiate after:

- [ ] https://github.com/mc2-center/data-models/issues/157 
- [ ] #145 

Details within existing docs. Overall, process is the same, but metadata are different.

**Comment by aditya-nath-sage** [comment]
Created the dataset manifest: https://docs.google.com/spreadsheets/d/1_Kvhbu5-0IKyRGxXR8dq8PONFcQ7gKCPEjTMMyJuhno/edit?usp=drive_link

**Comment by aclayton555** [comment]
24-11/12 - Cross check that these are captured within Nov batch captured in #154 . If so, these should be uploaded by end of 2025.

**Comment by aditya-nath-sage** [comment]
Uploaded publications!

**Comment by aditya-nath-sage** [comment]
[ Dataset manifest is available for November](https://docs.google.com/spreadsheets/d/1_Kvhbu5-0IKyRGxXR8dq8PONFcQ7gKCPEjTMMyJuhno/edit?usp=drive_link) 
@Bankso can you see if the manifest is in the correct format to be uploaded?

**Comment by aditya-nath-sage** [comment]
Datasets for all months in backlog (May 2024-Feb 2025) have been uploaded!
