### ISSUE TITLE
[July - Sep] [Tools] Curation Workflow Tracking

### ISSUE THREAD

**Issue by aditigopalan** [mc2-center/data-models#139]
This ticket tracks curation workflow progression. 

Note: It is possible for work to take place simultaneously in the three sections with overlapping periods, allowing curation workflows for different months to coincide.

### **1. Curation and Annotation**
  - [x] Run Pubmed crawler to generate PublicationView manifest [205 publications generated, long sprint anticipated]
  - [x] Send Amber and Jineta a copy of the PublicationView manifest from latest crawl to review for MC2 Center Newsletter publication highlights
  - [ ] Send Amber "News from CCKP" for MC2 Center Newsletter
  - [x] Annotate publications in PublicationView manifest [In progress]
  - [x] Generate ToolView and DatasetView manifests based on PublicationView manifest
  - [x] Run the [automated curation workflow](https://github.com/mc2-center/mc2-center-dcc/tree/main/annotations) to upload publications, datasets and tools [This includes splitting manifests, processing and validating manifests, generating target synapse IDs for upload, schema updates, upload to synapse and (in progress) a validation check for uploads)
  - [x] Generate UNION tables 
  - [x] QC of staging tables
  - [x] Performing automate portal sync to CCKP
  - [x] Validate data on the CCKP
  
  **Status check [Plan to report numbers for each category following pubmed crawl]:** 
  
  - [ ] Publication upload [ ]
  - [ ] Tool upload [ ]
  - [ ] Data set upload [ ]

### **2. Data model**  
  - [ ]  Update valid values in the data model and build
  - [ ]  Generate templates from new model
  - [ ]  Release new model version [no changes, no release]
  - [ ]  Update DCA config [no changes, no update]

### **3. Contributor Engagement**
  - [ ] Emails to contributors (by grant) with info on newly added manifests, link to project, DCA, and instructions on review, annotation, validation, and submission, as applicable
  - [ ] Jira Help Desk ticket tracking, review, triage, with data model updates, as needed (TBD)
  - [ ] Annotation gap-filling of DatasetView and ToolView manifests

**Comment by aclayton555** [comment]
24-11/12: Unlikely to get to this this sprint. Move back to backlog. Should be initiated after:

- [ ] https://github.com/mc2-center/data-models/issues/157
- [ ] https://github.com/mc2-center/data-models/issues/145
- [ ] https://github.com/mc2-center/data-models/issues/138

**Comment by aditya-nath-sage** [comment]
Tools manifest completed, backlog from June 2024-Feb 2025 is completed : https://docs.google.com/spreadsheets/d/1hJqp-DCIKQss6-aVd92AtvmDnTWxaCcfKxArSy_anOU/edit?usp=sharing
