### ISSUE TITLE
[End of 2024] [Grants] Curation Workflow Tracking

### ISSUE THREAD

**Issue by aclayton555** [mc2-center/data-models#145]
NCI funds new grants throughout the year. We typically curate and add these to the CCKP twice per year, or wait until there is a big batch to add since this process is not trivial. 

Ideally by the end of Q4 2024, we need to add the following 11 grants to our repertoire of infrastructure, curation, and listing on the CCKP: 

- MetNet (U01 CA284085, U01 CA283749, U01 CA289564, U01 CA293470)
- TEC (R37 CA279722, R01 CA290115, R01 CA279948, R01 CA281216, R01 CA292382)
- PS-ON (U01 CA290442, U01 CA293853)

Information on all of these grants is available in https://reporter.nih.gov/ and can be searched by the grant numbers listed above. Notably, none of these are U54 grants, so there is no need to curate sub-projects (typically done with the ProjectView manifest) for these grants.

Historically, we tracked the grant curation process in Jira, with the following steps (please take a look at the [last round of grant curation](https://sagebionetworks.jira.com/browse/CPO-813) for additional context and historical roles). We have an opportunity to re-visit this process to 1) consider opportunities for streamlined grant metadata extraction and infrastructure setup automation 2) formalize an updated grant curation SOP in the context of our latest infrastructure and required steps. I understand that @Bankso and @aditya-nath-sage may have some ideas here.

- [x] Curate list of grants to add (above)
- [x] Populate GrantView manifest with grants to be added and identify new terms to be added to the data model
- [x] Assign themes to new MC2 grants, ideally based on existing themes
- [x] Update data model with new terms: new themes, grant numbers, etc
- [x] Make further updates to GrantView manifest, as needed (following data model updates)
- [x] Create Synapse projects for new MC2 grants with default wiki info and resource sub-folders
- [x] GrantView manifest validated and uploaded + syncing scripts updated as needed
- [x] Sync newly ingressed grant data to Portal - Grants Merged table
- [x] Validate updated grant information on portal
- [x] Push and confirm theme graphs on CCKP homepage have been updated (there is an action for Github for this that Verena or Ashley have controlled in the past)
- [x] Ensure scopes are updated for new grants: DCA, UNION tables, etc.
- [x] Ensure pubmed crawler is successfully picking up resources for new grants

By the end of this round, I am hoping we can develop an updated SOP for grant curation.

**Comment by aditya-nath-sage** [comment]
Have been unable to work on grants curation this sprint

**Comment by aditya-nath-sage** [comment]
Will work on grants curation for feb 2025 sprint

**Comment by aclayton555** [comment]
@aditya-nath-sage just checking if you have been able to get started on this?

**Comment by aditya-nath-sage** [comment]
The Grant manifest for all the grants specified in this ticket has been filled out! Uploading all the tables later this week with the help of @Bankso

**Comment by aclayton555** [comment]
@aditya-nath-sage great to hear! Can you please update the checklist items in the description of this ticket as this moves forward?

**Comment by Bankso** [comment]
New GrantView information is uploaded with Synapse projects + teams created. The one thing missing before we push to the portal are themes - @aclayton555 do we have the themes for the new grants documented somewhere already? I don't think I've been the one who assigned these in the past

**Comment by aclayton555** [comment]
I assumed the themes would have been filled in with the GrantView manifest before upload, but apologies if this was unclear in the steps. Historically, Julie was responsible for assigning themes to grants, then this was delegated to @jaybee84 . Jineta, do you have time to do this, or do you want to delegate this role to someone else on the team? To the extent possible, grants should be assigned to one of the existing themes, which are described in this table: https://www.synapse.org/Synapse:syn35369899/tables/

**Comment by jaybee84** [comment]
Can someone provide the manifest of grants? I can take a look and see.

**Comment by Bankso** [comment]
@jaybee84 No problem, the manifest with new grant metadata is here: https://docs.google.com/spreadsheets/d/1CMjpi5nq84Y82DLWC0yy3iK73wjpMlk7-cPnyuH1-O8/edit?gid=0#gid=0

**Comment by jaybee84** [comment]
@Bankso Themes have been added.

**Comment by Bankso** [comment]
New grants have been synced to the portal and I validated that at least one entry is showing up as a Grant Details page. Scope of [All Data Files V2](https://www.synapse.org/Synapse:syn27210848/tables/) has been updated to include the 11 new projects. UNION table scopes will be updated as needed during the pre-sync metadata QC process.

@aclayton555 / @vpchung please let me know if you see any issues or if it would be helpful for me to handle the theme update workflow

**Comment by vpchung** [comment]
> Push and confirm theme graphs on CCKP homepage have been updated

The workflow triggers on the 1st of every month!  For this ticket, should a manual run be triggered ?

**Comment by aclayton555** [comment]
Can we push a manual run so that we have the latest in great to point DevDocs to, and to use in prep for AACR (rather than waiting until April 1). Thanks!

**Comment by vpchung** [comment]
Done - I now see 154 total grants on the graph but please double-check whether the theme numbers are as expected:

![Image](https://github.com/user-attachments/assets/909d7ac1-13f1-477e-affe-b077b1e915dd)

**Comment by aclayton555** [comment]
This looks right to me!!! Thank you!

And I can confirm that I did some additional validation on the details pages. Looks great!

If I recall correctly, there is nothing we specifically need to do to update the scope of the pubmed crawler (it crawls based on the grant numbers in our database). If that is correct i think we can proceed to close this out!

**Comment by aditya-nath-sage** [comment]
Ran the pubmed crawler as a check and the new grants are showing up on the PubMed crawler excel output now!

**Comment by aclayton555** [comment]
Fantastic! Thanks Aditya! Let's proceed to close!
