### ISSUE TITLE
[November] Curation Workflow Tracking

### ISSUE THREAD

**Issue by aditya-nath-sage** [mc2-center/data-models#154]
This ticket tracks curation workflow progression.

Note: It is possible for work to take place simultaneously in the three sections with overlapping periods, allowing curation workflows for different months to coincide.

1. Curation and Annotation

- [x]  Run Pubmed crawler to generate PublicationView manifest [205 publications generated, long sprint anticipated]
- [x]  Send Amber and Jineta a copy of the PublicationView manifest from latest crawl to review for MC2 Center Newsletter publication highlights
- [x]  Send Amber "News from CCKP" for MC2 Center Newsletter
- [x]  Annotate publications in PublicationView manifest [In progress]
- [x]  Generate ToolView and DatasetView manifests based on PublicationView manifest
- [x]  Run the [automated curation workflow](https://github.com/mc2-center/mc2-center-dcc/tree/main/annotations) to upload publications, datasets and tools [This includes splitting manifests, processing and validating manifests, generating target synapse IDs for upload, schema updates, upload to synapse and (in progress) a validation check for uploads)
- [x]  Generate UNION tables
- [x]  QC of staging tables
- [x]  Performing automate portal sync to CCKP
- [x]  Validate data on the CCKP
- [ ] Status check [Plan to report numbers for each category following pubmed crawl]:

- [x]  Publication upload 
- [x]  Tool upload 
- [x]  Data set upload 

2. Data model 

- [x] If no updates needed, no need to update data model

- [ ] If updated, do these steps:

1. Update valid values in the data model and build
2. Generate templates from new model
3. Release new model version [[v6.0.0](https://github.com/mc2-center/data-models/releases/tag/v6.0.0)]
4. Update DCA config [https://github.com/Sage-Bionetworks/data_curator_config/pull/193]

3. Contributor Engagement

- [ ]  Emails to contributors (by grant) with info on newly added manifests, link to project, DCA, and instructions on review, annotation, validation, and submission, as applicable
- [ ]  Jira Help Desk ticket tracking, review, triage, with data model updates, as needed (TBD)
- [ ]  Annotation gap-filling of DatasetView and ToolView manifests

**Comment by aditya-nath-sage** [comment]
Publication manifest manually annotated: https://docs.google.com/spreadsheets/d/15-VbezqGbMkUpR9A-PYS_yIYWKfAdafFOFmHiuXhjic/edit?usp=sharing

**Comment by aditya-nath-sage** [comment]
Datasets manifest: https://docs.google.com/spreadsheets/d/1_Kvhbu5-0IKyRGxXR8dq8PONFcQ7gKCPEjTMMyJuhno/edit?usp=sharing

**Comment by aclayton555** [comment]
25-11/12 - @aditya-nath-sage can proceed with upload of these and October Pub batch (see #157 ). Proceed and ping Orion or Aditi to cross-check as needed.

**Comment by aditya-nath-sage** [comment]
Uploaded publications!

**Comment by aditya-nath-sage** [comment]
After double checking with Orion was able to identify some issues with scripts for upload and was able to fix some of them, will need further review in new year. Publications should be uploaded nonetheless, will also need checking to see whether they were put in properly in the new year.

**Comment by Bankso** [comment]
I ran QC on the publication view union table and found that 51 new pubs had been added. 

The only issue I noticed initially was the high number of duplicate entries that were flagged, of which there were 12. When looking into the entityIds that were referenced in the fields with duplicate entries, I noticed a couple things:
- some of the entries are missing their entityId, which is making it difficult to determine where the redundant entries are coming from (example: [top two rows of the union table](https://www.synapse.org/Synapse:syn52752398/tables/#query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjUyNzUyMzk4IiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAibGltaXQiOjI1LCAic29ydCI6W3siY29sdW1uIjoiUHVibGljYXRpb25WaWV3X2lkIiwgImRpcmVjdGlvbiI6IkRFU0MifV19)) 
-  some of the grant numbers in the tables were different than expected (example: [bottom two rows of this table](https://www.synapse.org/Synapse:syn52565158/tables/))

I will continue investigating to see if I can identify the source of the extra entries and the extent of the grant number mismatch, but I think we should also take another look at the upload pipeline to diagnose and fix the source of the misaligned upload. There are likely some steps we can modify to improve functionality (like how we generate the target folder reference sheet)

Based on what I've seen so far, I have two guesses where the upload could have gone wrong:
- the grant number --> upload folder reference file is misaligned, and/or
- the validation script clipped some manifests from the submission queue and uploaded manifests to the incorrect tables

**Comment by Bankso** [comment]
Some initial observations from investigating tables:
Examining entries for PublicationView_id: 39438697, derived from grants CA238720 and CA283114
- [The CA283114 table](https://www.synapse.org/Synapse:syn64423865/tables/) had a schema mismatch, which apparently was causing an extra entry to be listed in the union table. After I updated the schema order, the extra entry was removed
- The publication listed in the table I linked above [corresponds to two grant numbers](https://www.synapse.org/Synapse:syn52752398/tables/#query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjUyNzUyMzk4IFdIRVJFIFB1YmxpY2F0aW9uVmlld19pZCA9ICczOTQzODY5NyciLCAiaW5jbHVkZUVudGl0eUV0YWciOnRydWUsICJsaW1pdCI6MjUsICJzb3J0IjpbeyJjb2x1bW4iOiJQdWJsaWNhdGlvblZpZXdfaWQiLCAiZGlyZWN0aW9uIjoiREVTQyJ9XX0=), but the CA238720 entry is missing its entityId
- I located the synId of the [source table for grant CA238720](https://www.synapse.org/Synapse:syn52565432/tables/) and found that there is a PublicationView_id: 39438697 entry here, but it is missing an entityId
- Interestingly, there is another entry corresponding to the PublicationView_id 39438697, but it is in a [table belonging to grant CA244100](https://www.synapse.org/Synapse:syn52565485/tables/)
  - This entry has an entityId of syn64423865 (identical to the CA283114 table I linked above)
  - This indicates that my schema fix above, which removed the third entry, just made the CA283114 and CA244100 entries identical, leading them to be merged in the union table

Based on that set of observations, this would suggest the following may be true:
- Some or all tables were updated with a mix of entries corresponding to correct and incorrect grant numbers
- Entries uploaded to tables matching their grant number did not necessarily have an entityId assigned during upload
- Entries uploaded to tables **not matching** their grant number **did** have an entityId assigned **and the entityIds seem to correspond with the correct grant number table**

Next steps 
- Identify which tables were updated most recently
- Identify a pattern associated with the entries uploaded to incorrect grant-specific tables, if possible
- Remove incorrect/redundant entries

Further investigation is needed to:
- Determine why entries were uploaded without entityIds assigned
- Determine how entries were uploaded to incorrect tables

Based on the info we gather here, we can implement fixes to limit the chances of this occurring again

**Comment by Bankso** [comment]
Update on investigation:

I wasn't able to determine a pattern with respect to the incorrect uploads - it seemed mostly random - but there were no situations I encountered where an entry was uploaded to the incorrect table instead of the correct table. That is, all the entries in wrong tables were accompanied by correct entries in the correct tables.

One consistent thing was that the entries in the wrong tables always had the correct entityId listed, but in most/all corresponding entries in the correct tables, the entityId was missing.

Since there wasn't a pattern and it was unclear which tables had incorrect entries, I used the output from `union_qc.py` to manually resolve issues. 
Command: `python utils/union_qc.py -l syn52752398 -c /Users/obanks/config.yml -m -s -db`
Updated entries from `union_qc.py`: https://docs.google.com/spreadsheets/d/1bNQUzbucIgjCzsbPkeGNy70gJPEAWP2IJMZwdmR2U98/edit?gid=0#gid=0
Validation output with mapping to order in updated entries: https://docs.google.com/spreadsheets/d/1bNQUzbucIgjCzsbPkeGNy70gJPEAWP2IJMZwdmR2U98/edit?gid=1693217660#gid=1693217660

Next steps for the database are to finish fixing validation errors and revalidate, then we can push to prod. 

I haven't determined what changes we should make to our scripts, yet, but we should probably add some additional checks/validation to confirm things like:
- if all the identifiers listed in a manifest were uploaded to Synapse
- if all identifiers were uploaded to tables that correspond with their listed grant number(s)
- if the entityId added to the manifest matches the expected table synId
- ? not sure what else yet

**Comment by Bankso** [comment]
I wanted to note some ideas related to process and QC improvements for curation uploads:
- test if adding a `wait` period in manifest validation and/or submission by `upload-manifests.py` would help with manifests being uploaded to the incorrect Synapse projects
  - 1/17/25 UPDATE: I ended up adding some logic to our upload script that limits manifest submission to one at a time. While this takes ~6 hrs for ~130 manifests, there were no erroneous entries added and only four uploads failed to assign `entityId` values. These were easily fixed by reuploading.
  - this comes from observations during recent metadata upload, where `schematic upload` commands submitted via `subprocess` were getting their wires crossed. 
    - I wasn't able to copy the error log, but I saw several instances where `schematic` lost track of manifests it was trying to submit
    - This seemed to happen when it was renaming, copying, and adding `id` and `entityId` columns to the manifests. This makes some sense, because it renames the manifest to `synapse_storage_manifest_grantview.csv` when submitting. If `subprocess` is running a bunch of these at the same time, it seems likely that there could be a mix up
    - Ultimately, a subset of manifests were lost during the upload and had to be regenerated
  - In addition, a subset of the deleted manifests were still uploaded to Synapse, which produced some strange results:
    - some entries were uploaded to tables corresponding to synIds which were one digit back (e.g., syn1234567 vs syn1234566), generating redundant entries
    - in all cases, the correct tables were generated in the expected Synapse projects, but the deleted manifest was not uploaded. If it was uploaded, it went to the wrong project, as noted above
    - I was able to fix the missing uploads by repeating the upload process
    - I used `upload_validation.py` to determine which manifests had been uploaded
    - I used `count_table_rows.py` to identify Grant View tables with more than one entry, of which there should only be two
- add some code to `gen-mp-csv.py` to handle folder info for Synapse projects with multiple associated grants (e.g., CaST, MC2)
  - I'm thinking a simple mapping table for the problematic grant numbers will be sufficient
  - 1/17/25 UPDATE: I did this for the CaST grant and it seemed to work just fine
- if needed, we can expand on this row counting script I threw together, [here](https://github.com/mc2-center/mc2-center-dcc/blob/add-utils-11-24/utils/count_table_rows.py) to report the number of entries added to each table and the number of expected entries
- With the addition of Grant View metadata to grant-specific Synapse projects, we can leverage cross-manifest validation, to ensure that "GrantView Key" and/or "Study Key" are contained in "GrantView_id" and "Study_id" columns, respectively

**Comment by aclayton555** [comment]
25-1 Close-out

- Publications though Jan crawl should be ready to proceed with upload
- Datasets Nov through Jan should be ready to upload
- Tools - should be able to pick this up and catch up

**Comment by aditya-nath-sage** [comment]
Publication curation for Jan 2025: https://docs.google.com/spreadsheets/d/1CuKG7-5DD3tKiEw3uco5AxB2kmbkghvoQakGhA_DzmQ/edit?usp=drive_link
@Bankso can you see if this manifest is in the correct format to be uploaded?

**Comment by Bankso** [comment]
All content uploaded to Synapse has been synced to the CCKP
