### ISSUE TITLE
[October] [Pubs] Curation Workflow Tracking

### ISSUE THREAD

**Issue by aditya-nath-sage** [mc2-center/data-models#157]
This ticket tracks curation workflow progression.

Note: It is possible for work to take place simultaneously in the three sections with overlapping periods, allowing curation workflows for different months to coincide.

1. Curation and Annotation

- [x] Run Pubmed crawler to generate PublicationView manifest 
- [x] Send Amber and Jineta a copy of the PublicationView manifest from latest crawl to review for MC2 Center Newsletter publication highlights (https://sagebionetworks.jira.com/browse/CPO-1339)
- [x] (Aditi) Send Amber "News from CCKP" for MC2 Center Newsletter (https://sagebionetworks.jira.com/browse/CPO-1338)
- [x] Annotate publications in PublicationView manifest [In progress]
- [x] Generate ToolView and DatasetView manifests based on PublicationView manifest
- [x] (Orion) Run the [automated curation workflow](https://github.com/mc2-center/mc2-center-dcc/tree/main/annotations) to upload publications, datasets and tools [This includes splitting manifests, processing and validating manifests, generating target synapse IDs for upload, schema updates, upload to synapse and (in progress) a validation check for uploads)
- [x] QC of staging tables
- [x] Performing automate portal sync to CCKP
- [x] Validate data on the CCKP

Status check [Plan to report numbers for each category following pubmed crawl]:

Publication upload
2. Data model [No new updates]
- [ ] Update valid values in the data model and build
- [ ] Generate templates from new model
- [ ] Release new model version [no changes, no release]
- [ ] Update DCA config [no changes, no update]

**Comment by aditya-nath-sage** [comment]
Ran the Curation workflow scripts (no datasets since I didn't curate them this time).
No issues, should be uploaded!

**Comment by aclayton555** [comment]
25-11/12 - Pubs have been annotated and are ready for upload

**Comment by aclayton555** [comment]
25-1 Ready to proceed with upload. Previously found some duplicates from upload process, so have been cross-checking scripts. Orion has been checking for and cleaning up duplicate entries.

@aditya-nath-sage to send @Bankso the manifest to test upload with updated table schemas. Aditya please link manifest here. Orion will cross check schemas then Aditya can proceed with upload. Should be able to complete today.

**Comment by aditya-nath-sage** [comment]
Manifests uploaded!

**Comment by aclayton555** [comment]
@aditya-nath-sage can we keep this open until all steps in the description have been completed (and pubs have been validated on CCKP). Or, if this tracking is captured in another ticket/batch, please link that here.

**Comment by Bankso** [comment]
@aditya-nath-sage could you please link all the publication manifests you've prepared over the last few months and indicate which ones have been uploaded? I'd like to compare the entries in the manifests with the entries in the union tables

**Comment by aditya-nath-sage** [comment]
Nov 2024: https://docs.google.com/spreadsheets/d/15-VbezqGbMkUpR9A-PYS_yIYWKfAdafFOFmHiuXhjic/edit?usp=drive_link
Jan 2025: https://docs.google.com/spreadsheets/d/1CuKG7-5DD3tKiEw3uco5AxB2kmbkghvoQakGhA_DzmQ/edit?usp=drive_link

these are the two I have uploaded, nov had some issues but I believe the last time I uploaded should have worked, and the previous times caused some of the bad entries you had seen

**Comment by Bankso** [comment]
@aditya-nath-sage thank you! It looks like the Nov 2024 uploads worked, but for many of the entries, the annotations listed in that sheet are missing; I'm guessing this has to do with the strange upload behavior we observed. As far as I can tell, though, the Jan 2025 entries did not make it into the project tables. 

I'm thinking that `upload-manifests.py` is the source of the issue here, since it is configured to 1) validate each metadata sheet and 2) add manifests to the upload queue only if they passed validation. This is intentional, but I think the cross-manifest validation rule for `Key`-type attributes (e.g., `GrantView Key`) is causing all the manifests to fail validation. While it is best to validate the metadata before it gets uploaded, you can pass the flag `-v` at runtime to perform validation and ignore its output or `--skip` to bypass validation all together. This is helpful when you're uploading previously validated metadata or if you're trying to diagnose validation issues. 

While it might very well be the case that we just need to remove the cross-manifest validation rules for `Key` attributes, I am going to try adding the `-ps`/`--project_scope` flag to our validation calls. If that works, I'll update `gen-mp-csv.py` to not remove the `grantId` column, which we can use as input for the `-ps` flag during validation, and update input handling in `upload-manifests.py` to pull the grant Synapse project Id.

EDIT 2/5/2025: adding `-ps` to the validation call seems to have worked, as I am now seeing successful validation messages in my terminal. For reference, the `schematic` call looks like this:
`schematic model -c /Users/obanks/config.yml validate -dt PublicationView -mp CA209975_publication.csv -ps syn7315805`
`gen-mp-csv.py` and `upload-manifests.py` have been updated to allow `-ps` flag usage

Separately, I have the Nov and Jan PublicationView entries uploading right now. I started from this sheet, where I collated both sets of PublicationView entries linked above: https://docs.google.com/spreadsheets/d/1CuKG7-5DD3tKiEw3uco5AxB2kmbkghvoQakGhA_DzmQ/edit?gid=232869329#gid=232869329

For reference, these are the commands I'm running:

`python split_manifest_grants.py PublicationView.csv publication output/pubs_2-5-2025 --csv`
`python gen-mp-csv.py output/pubs_2-5-2025 output/pubs_paths_2-5-25.csv publications`
`python processing-splits.py output/pubs_2-5-2025`
`python schema_update.py output/pubs_paths_2-5-25.csv Publication`
`python upload-manifests.py -m output/pubs_paths_2-5-25.csv -t PublicationView -c /Users/obanks/config.yml --skip`

**Comment by Bankso** [comment]
Update 2/14/25 - PublicationView manifests for Oct 2024, Nov 2024, and Jan 2025 have been uploaded. Syncing script updates are in progress, as noted in #159

**Comment by aditya-nath-sage** [comment]
FInal Publication manifests (From 4/24-9/24) all uploaded. Feb 2025 Publication manifests are also uploaded
